version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.3
workflows:
  start_setup:
    jobs:
      - path-filtering/filter:
          name: 'setup front lint check and backend test'
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/front_lint_check_and_backend_test.yml
          mapping: |
            src/.* is_front_lint_check true
            src-tauri/.* is_backend_test true
